DATA SEGMENT
ASCII DB 31H, 32H, 33H, 34H, 35H, 36H, 37H, 38H, 39H, 30H
 DB 100 DUP(00H)
DATA ENDS
CODE SEGMENT
ASSUME CS: CODE, DS: DATA
START: MOV AX, DATA
 MOV DS, AX
 MOV CX, 10
 MOV BX, 0000H
BACK: MOV AL, [BX]
 AND AL, 0FH
 MOV [BX+16], AL
 INC BX
 LOOP BACK
 INT 3H
CODE ENDS
END START

; To Execute
; Open DOSBOX
; Z:\> Mount D ~(curl)
; Z:\> D:
; • D:\>cd MASM
; • D:\Masm>
; • D:\MASM > MASM EXP2.asm
; • D:\MASM > LINK EXP2.obj
; • D:\MASM >TD EXP1.exe
; • RUN
; • VIEW
; • ANOTHER
; • DUMP